name: Workshop CI
on:
  pull_request:
    branches:
      - main
      
jobs:
  sample_echo:
    runs-on: Ubuntu-latest

    steps:
      - name: Checkout code # name of step
        uses: actions/checkout@v2 # uses package
        with: # settings
          token: $ {{ secrets.WORKSHOP_TOKEN }} # setting 1

      - name: Check files
        run: |
          ls -lah # show files in current directory
